title: <p align="center"> Josafat Choque </p>

logo: "images/Efímera-Belleza.jpg"

description:
  <p align="center">
  <a href="Not found">LinkedIn</a> |
  <a href="En búsqueda">GitHub</a>
  </p>
  
  <p align="justify">
  Soy estudiante de Ing. Civil Eléctrica Universidad de la Frontera, Chile.
  <br><br>
  ---------------------------
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
